name: Fetch and Save JSON Data

on:
  schedule:
    - cron: '*/5 * * * *' 
  push:
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Current Minute and Build URL
        id: build_url
        run: |
          MINUTE=$(date +%M)
          NEXT_MINUTE=$(( (10#$MINUTE + 1) % 60 ))
          if [ "$NEXT_MINUTE" -eq 0 ]; then
            NEXT_MINUTE=60
          fi
          echo "minute=$NEXT_MINUTE" >> $GITHUB_OUTPUT
          echo "url=https://jsonplaceholder.typicode.com/todos/$NEXT_MINUTE" >> $GITHUB_OUTPUT

      - name: Fetch JSON and Save to test.json
        run: |
          curl -s "${{ steps.build_url.outputs.url }}" -o test.json

      - name: Commit and Push test.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          
          git add test.json
          git commit -m "Update test.json at minute ${{ steps.build_url.outputs.minute }}" || echo "No changes to commit"
          git push
